"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var classes_1 = require("./classes");
var wearableFitness = new classes_1.Startup("Wearable Fitness", "Wearable", "Tecnologie per misurare i tuoi valori mentre fai sport", ["Smartwatch", "Anelli tech"]);
var innovationSportlab = new classes_1.Startup("Innovation SportLab", "Attrezzature", "Nuove attrezzature innovative per l'allenamento", ["Panche", " Manubri", " Tapirulan", " Cyclette"]);
var tennisWorld = new classes_1.Startup("Tennis World", "Tennis", "Articoli a 360 gradi per il tennis", ["Racchette", " Palline", " Cappellini", " Reti"]);
var incentivoMax = new classes_1.Incentivo(8111, "incentivo massimo", 8000, ["emissioni zero", " prodotti ecosostenibili", " prodotti costruiti in italia"]);
var incentivoMid = new classes_1.Incentivo(6011, "incentivo medio", 6000, ["prodotti ecosostenibili", " prodotti costruiti in italia"]);
var incentivoMin = new classes_1.Incentivo(4001, "incentivo minimo", 4000, ["prodotti ecosostenibili"]);
var marco = new classes_1.Cittadino("Marco", "Rossi", 34, ["Tennis", " Ping Pong"]);
var sofia = new classes_1.Cittadino("Sofia", "Verdi", 27, ["Nuoto", " Vela"]);
var matteo = new classes_1.Cittadino("Matteo", "Bianchi", 29, ["Calcio", " Rugby"]);
wearableFitness.riceviIncentivo(incentivoMin);
incentivoMin.assegnaAStartup(wearableFitness);
sofia.partecipaAttività(wearableFitness);
innovationSportlab.riceviIncentivo(incentivoMax);
incentivoMax.assegnaAStartup(innovationSportlab);
matteo.partecipaAttività(innovationSportlab);
